In [ ]:
#!pip install pynvjitlink

#import pynvjitlink

ERROR: Could not find a version that satisfies the requirement pynvjitlink (from versions: none)
ERROR: No matching distribution found for pynvjitlink


In [ ]:
!pip install pynvjitlink-cu12

import pynvjitlink

from numba import config

config.CUDA_ENABLE_PYNVJITLINK = 1

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.9/46.9 MB 13.4 MB/s eta 0:00:00


In [ ]:
!uv pip install -q --system numba-cuda==0.4.0
from numba import config

config.CUDA_ENABLE_PYNVJITLINK = 1

In [ ]:
import numpy as np
from numba import cuda

cuda.gpus
cuda.detect()
cuda.select_device(0)

Found 1 CUDA devices
id 0             b'Tesla T4'                              [SUPPORTED]
                      Compute Capability: 7.5
                           PCI Device ID: 4
                              PCI Bus ID: 0
                                    UUID: GPU-03bc8767-60a1-e1d0-ac06-631224108fbb
                                Watchdog: Disabled
             FP32/FP64 Performance Ratio: 32
Summary:
	1/1 devices are supported


<weakproxy at 0x78774d003f10 to Device at 0x78774e02d5b0>

In [ ]:
from numba import cuda
cc_cores_per_SM_dict = {  (2,0) : 32,  (2,1) : 48, (3,0) : 192, (3,5) : 192, (3,7) : 192, (5,0) : 128, (5,2) : 128, (6,0) : 64, (6,1) : 128, (7,0) : 64, (7,5) : 64, (8,0) : 64, (8,6) : 128, (8,9) : 128, (9,0) : 128 }

device = cuda.get_current_device()
sms = getattr(device, "MULTIPROCESSOR_COUNT")
cc = device.compute_capability
cores_por_sm = cc_cores_per_SM_dict.get(cc)
cores_totales = cores_por_sm * sms
print("GPU compute capability: ", cc)
print("Número de SM: ", sms)
print("Número de cores: ", cores_totales)


GPU compute capability:  (7, 5)
Número de SM:  40
Número de cores:  2560


In [ ]:
from numba.cuda.cudadrv import enums
from numba import cuda

device = cuda.get_current_device()
attribs = [name.replace("CU_DEVICE_ATTRIBUTE_", "") for name in dir(enums) if name.startswith("CU_DEVICE_ATTRIBUTE_")]
for attr in attribs:
    print(attr, "=", getattr(device, attr))

ASYNC_ENGINE_COUNT = 3
CAN_MAP_HOST_MEMORY = 1
CAN_USE_HOST_POINTER_FOR_REGISTERED_MEM = 1
CLOCK_RATE = 1590000
COMPUTE_CAPABILITY_MAJOR = 7
COMPUTE_CAPABILITY_MINOR = 5
COMPUTE_MODE = 0
COMPUTE_PREEMPTION_SUPPORTED = 1
CONCURRENT_KERNELS = 1
CONCURRENT_MANAGED_ACCESS = 1
COOPERATIVE_LAUNCH = 1
COOPERATIVE_MULTI_DEVICE_LAUNCH = 1
ECC_ENABLED = 1
GLOBAL_L1_CACHE_SUPPORTED = 1
GLOBAL_MEMORY_BUS_WIDTH = 256
GPU_OVERLAP = 1
HOST_NATIVE_ATOMIC_SUPPORTED = 0
INTEGRATED = 0
IS_MULTI_GPU_BOARD = 0
KERNEL_EXEC_TIMEOUT = 0
L2_CACHE_SIZE = 4194304
LOCAL_L1_CACHE_SUPPORTED = 1
MANAGED_MEMORY = 1
MAX_BLOCK_DIM_X = 1024
MAX_BLOCK_DIM_Y = 1024
MAX_BLOCK_DIM_Z = 64
MAX_GRID_DIM_X = 2147483647
MAX_GRID_DIM_Y = 65535
MAX_GRID_DIM_Z = 65535
MAX_MAX_TEXTURE_2D_MIPMAPPED_HEIGHT = 32768
MAX_PITCH = 2147483647
MAX_REGISTERS_PER_BLOCK = 65536
MAX_REGISTERS_PER_MULTIPROCESSOR = 65536
MAX_SHARED_MEMORY_PER_BLOCK = 49152
MAX_SHARED_MEMORY_PER_BLOCK_OPTIN = 65536
MAX_SHARED_MEMORY_PER_MULTIPROCESSOR = 65536
MAX_S


#Lanzamiento de un kernel



In [ ]:


@cuda.jit
def un_kernel(x, y, out):
  pass

x = np.ones(256)
y = x * 2
out = np.empty_like(x)
block_size = 32
num_blocks = 1000
un_kernel[num_blocks, block_size](x, y, out)
print(out)


[6.54410941e-310 6.54410941e-310 3.84335840e-315 3.84335840e-315
 4.94065646e-324 3.84335871e-315 3.84336030e-315 4.94065646e-324
 3.84335883e-315 3.84335887e-315 1.18575755e-322 6.54410904e-310
 9.88131292e-324 3.84335927e-315 3.45845952e-323 6.36598738e-314
 1.18575755e-322 6.54410757e-310 2.97079411e-313 3.18299369e-313
 1.27319747e-313 1.69759663e-313 1.03753786e-322 3.84335911e-315
 6.54410783e-310 6.54402282e-310 1.27319747e-313 4.03179200e-313
 4.94065646e-324 3.84335966e-315 3.84335970e-315 1.18575755e-322
 5.78950076e-317 1.90979621e-313 2.96439388e-323 4.24399158e-313
 4.45619116e-313 0.00000000e+000 3.84336002e-315 0.00000000e+000
 8.39911598e-323 3.84335935e-315 3.84335958e-315 3.84335994e-315
 1.27319747e-313 4.66839074e-313 2.96439388e-323 3.84335875e-315
 3.84336006e-315 0.00000000e+000 1.03753786e-322 3.84335998e-315
 6.54410907e-310 4.94065646e-324 3.45845952e-323 4.66839074e-313
 0.00000000e+000 3.84336077e-315 0.00000000e+000 4.94065646e-324
 3.84335864e-315 3.843360

/usr/local/lib/python3.12/dist-packages/numba_cuda/numba/cuda/cudadrv/devicearray.py:893: NumbaPerformanceWarning: Host array used in CUDA kernel will incur copy overhead to/from device.
  warn(NumbaPerformanceWarning(msg))


# Kernel minimalista con posicion absoluta manual

In [ ]:
@cuda.jit
def kernel_doblador(arreglo, log):

  posicion = cuda.threadIdx.x + cuda.blockIdx.x * cuda.blockDim.x

  if posicion < arreglo.size:
    arreglo[posicion] *= 2
    log[posicion][0] = posicion
    log[posicion][1] = cuda.threadIdx.x
    log[posicion][2] = cuda.blockIdx.x
    log[posicion][3] = cuda.blockDim.x


x = np.ones(256)
log = np.zeros(shape=(x.size, 4))

block_size = 32
num_blocks = 10
kernel_doblador[num_blocks, block_size](x, log)
print(x)
for record in log:
  print(record)


/usr/local/lib/python3.12/dist-packages/numba_cuda/numba/cuda/dispatcher.py:605: NumbaPerformanceWarning: Grid size 10 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))


[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[ 0.  0.  0. 32.]
[ 1.  1.  0. 32.]
[ 2.  2.  0. 32.]
[ 3.  3.  0. 32.]
[ 4.  4.  0. 32.]
[ 5.  5.  0. 32.]
[ 6.  6.  0. 32.]
[ 7.  7.  0. 32.]
[ 8.  8.  0. 32.]
[ 9.  9.  0. 32.]
[10. 10.  0. 32.]
[11. 11.  0. 32.]
[12.

/usr/local/lib/python3.12/dist-packages/numba_cuda/numba/cuda/cudadrv/devicearray.py:893: NumbaPerformanceWarning: Host array used in CUDA kernel will incur copy overhead to/from device.
  warn(NumbaPerformanceWarning(msg))


#Grid de menor tamaño que la estructura de datos

In [ ]:
@cuda.jit
def kernel_doblador(arreglo):
  #posicion = cuda.threadIdx.x + cuda.blockIdx.x * cuda.blockDim.x
  posicion = cuda.grid(1)
  #tamano_grid = cuda.blockDim.x * cuda.gridDim.x
  tamano_grid = cuda.gridsize(1)
  # for (i = posicion; i < arreglo.size; i+=tamano_grid)
  for i in range(posicion, arreglo.size, tamano_grid):
    arreglo[i] *= 2


x = np.ones(128)

block_size = 32
num_blocks = 2
kernel_doblador[num_blocks, block_size](x)
print(x)


[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2.]


/usr/local/lib/python3.12/dist-packages/numba_cuda/numba/cuda/dispatcher.py:605: NumbaPerformanceWarning: Grid size 2 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.12/dist-packages/numba_cuda/numba/cuda/cudadrv/devicearray.py:893: NumbaPerformanceWarning: Host array used in CUDA kernel will incur copy overhead to/from device.
  warn(NumbaPerformanceWarning(msg))


# Grid ajustable a estructura de datos

In [ ]:
import math
@cuda.jit
def kernel_doblador(x, y, out):
  posicion = cuda.grid(1)
  tamano_grid = cuda.gridsize(1)
  if posicion < x.size:
    out[posicion] = x[posicion] + y[posicion]


x = np.arange(500)
y = x * 2
x_device = cuda.to_device(x)
y_device = cuda.to_device(y)
out = np.empty_like(x)
out_device = cuda.device_array_like(x)

block_size = 32
num_blocks =  int(math.ceil(x.size / block_size))
kernel_doblador[num_blocks, block_size](x_device, y_device, out_device)
out = out_device.copy_to_host()
print(out)


[   0    3    6    9   12   15   18   21   24   27   30   33   36   39
   42   45   48   51   54   57   60   63   66   69   72   75   78   81
   84   87   90   93   96   99  102  105  108  111  114  117  120  123
  126  129  132  135  138  141  144  147  150  153  156  159  162  165
  168  171  174  177  180  183  186  189  192  195  198  201  204  207
  210  213  216  219  222  225  228  231  234  237  240  243  246  249
  252  255  258  261  264  267  270  273  276  279  282  285  288  291
  294  297  300  303  306  309  312  315  318  321  324  327  330  333
  336  339  342  345  348  351  354  357  360  363  366  369  372  375
  378  381  384  387  390  393  396  399  402  405  408  411  414  417
  420  423  426  429  432  435  438  441  444  447  450  453  456  459
  462  465  468  471  474  477  480  483  486  489  492  495  498  501
  504  507  510  513  516  519  522  525  528  531  534  537  540  543
  546  549  552  555  558  561  564  567  570  573  576  579  582  585
  588 

/usr/local/lib/python3.12/dist-packages/numba_cuda/numba/cuda/dispatcher.py:605: NumbaPerformanceWarning: Grid size 16 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))


# Multiplicacion matrices


In [ ]:
import math

@cuda.jit
def mult_matrices(a, b, c):
  ren, col = cuda.grid(2)
  if ren < c.shape[0] and col < c.shape[1]:
    suma = 0
    for i in range(a.shape[1]):
      suma += a[ren][i] * b[i][col]
    c[ren][col] = suma

block = (16, 16)
a = np.full((32, 12), 2, float)
b = np.full((12, 48), 4, float)
c = np.full((32, 48), 0, float)
a_device = cuda.to_device(a)
b_device = cuda.to_device(b)
c_device = cuda.device_array((32, 48))
grid_x = int(math.ceil(a.shape[0]/block[0]))
grid_y = int(math.ceil(b.shape[1]/block[1]))

mult_matrices[(grid_x, grid_y), block](a_device, b_device, c_device)
c = c_device.copy_to_host()
print(c)

/usr/local/lib/python3.12/dist-packages/numba_cuda/numba/cuda/dispatcher.py:605: NumbaPerformanceWarning: Grid size 6 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))


[[96. 96. 96. ... 96. 96. 96.]
 [96. 96. 96. ... 96. 96. 96.]
 [96. 96. 96. ... 96. 96. 96.]
 ...
 [96. 96. 96. ... 96. 96. 96.]
 [96. 96. 96. ... 96. 96. 96.]
 [96. 96. 96. ... 96. 96. 96.]]


# Filtro en imagen de Aguila

In [ ]:
from numba import cuda
import matplotlib.pyplot as plt
from skimage import data, io
import math
import numpy as np

@cuda.jit
def conv(pixels, output, size):
    row, col = cuda.grid(2)
    if (row + 2) < size[0] and (col + 2) < size[1] and row > 2 and col > 2:
      divisor = 75
      sum = pixels[row-2][col-1]/divisor + pixels[row-2][col]/divisor + pixels[row-2][col+1]/divisor + \
            pixels[row-1][col-1]/divisor + pixels[row-1][col]/divisor + pixels[row-1][col+1]/divisor + \
            pixels[row-0][col-1]/divisor + pixels[row-0][col]/divisor + pixels[row-0][col+1]/divisor + \
            pixels[row+1][col-1]/divisor + pixels[row+1][col]/divisor + pixels[row+1][col+1]/divisor + \
            pixels[row+2][col-1]/divisor + pixels[row+2][col]/divisor + pixels[row+2][col+1]/divisor
      output[row][col] = round(sum/15)


#eagle = data.eagle().astype(np.float32)
eagle = io.imread("eagle.png").astype(np.float32)
print(eagle.min(), eagle.max(), eagle)
plt.imshow(eagle, cmap="gray")
plt.show()

##(2019, 1826)
host_pixels = eagle
device_pixels = cuda.to_device(host_pixels)
device_output = cuda.device_array(host_pixels.shape)


threads_per_block = (16, 16)
blocks_x = math.ceil(eagle.shape[0] / threads_per_block[0])
blocks_y = math.ceil(eagle.shape[1] / threads_per_block[1])
grid = (blocks_x, blocks_y)

conv[grid, threads_per_block](device_pixels, device_output, eagle.shape)
plt.imshow(device_output.copy_to_host(), cmap="gray")
plt.show()